name: prisma_dart_issue_74
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  orm: ^2.4.6

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  lints: ^2.0.0
